---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tharnax-backend
  namespace: tharnax-web
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tharnax-cluster-reader
rules:
- apiGroups: [""]
  resources: ["nodes", "namespaces", "pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tharnax-backend-reader
subjects:
- kind: ServiceAccount
  name: tharnax-backend
  namespace: tharnax-web
roleRef:
  kind: ClusterRole
  name: tharnax-cluster-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tharnax-cluster-admin
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "persistentvolumes", "persistentvolumeclaims"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "statefulsets"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tharnax-backend-admin
subjects:
- kind: ServiceAccount
  name: tharnax-backend
  namespace: tharnax-web
roleRef:
  kind: ClusterRole
  name: tharnax-cluster-admin
  apiGroup: rbac.authorization.k8s.io 
