apiVersion: apps/v1
kind: Deployment
metadata:
  name: tharnax-web
  namespace: tharnax-web
  labels:
    app: tharnax-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tharnax-web
  template:
    metadata:
      labels:
        app: tharnax-web
    spec:
      serviceAccountName: tharnax-backend
      containers:
      - name: tharnax-web
        image: quentinc/tharnax:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: nfs-storage
          mountPath: /mnt/tharnax-nfs
          readOnly: true
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
      volumes:
      - name: nfs-storage
        hostPath:
          path: /mnt/tharnax-nfs
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: tharnax-web
  namespace: tharnax-web
  labels:
    app: tharnax-web
spec:
  selector:
    app: tharnax-web
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
