---
- name: Uninstall K3s from worker node
  hosts: worker2
  become: true
  tasks:
    - name: Check if K3s agent uninstall script exists
      stat:
        path: /usr/local/bin/k3s-agent-uninstall.sh
      register: k3s_agent_uninstall_script
    
    - name: Check if K3s uninstall script exists
      stat:
        path: /usr/local/bin/k3s-uninstall.sh
      register: k3s_uninstall_script
    
    - name: Run K3s agent uninstall script if exists
      command: /usr/local/bin/k3s-agent-uninstall.sh
      when: k3s_agent_uninstall_script.stat.exists
      ignore_errors: yes
    
    - name: Run K3s uninstall script if exists
      command: /usr/local/bin/k3s-uninstall.sh
      when: k3s_uninstall_script.stat.exists
      ignore_errors: yes
    
    - name: Remove K3s data directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/rancher/k3s
        - /etc/rancher/k3s
        - /var/lib/kubelet
      ignore_errors: yes
